# Generated by Django 4.1.7 on 2023-09-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'ordering': ['-dt_alteracao', '-dt_solicitacao', '-id']},
        ),
    ]
