# Generated by Django 4.1.7 on 2023-09-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0002_alter_ordemdeservico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'ordering': ['-dt_alteracao', '-dt_solicitacao']},
        ),
    ]
