# Generated by Django 4.2.5 on 2023-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0003_alter_ordemdeservico_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='secretaria',
            field=models.CharField(default='Nao existe', max_length=100, verbose_name='Secretaria'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='setor',
            field=models.CharField(default='Nao existe', max_length=100, verbose_name='Setor'),
        ),
    ]
