# Generated by Django 4.2.5 on 2023-10-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0005_alter_ordemdeservico_secretaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='possui_cnpj',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(max_length=7, null=True, unique=True, verbose_name='Matricula'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='secretaria',
            field=models.CharField(default='', max_length=100, verbose_name='Secretaria'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='setor',
            field=models.CharField(default='', max_length=100, verbose_name='Setor'),
        ),
    ]
