# Generated by Django 4.2.5 on 2023-10-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0006_remove_pessoa_bairro_remove_pessoa_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='setor',
        ),
    ]
