# Generated by Django 4.2.5 on 2023-10-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0007_remove_pessoa_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cep', models.CharField(max_length=9, null=True, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=64, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=128, null=True, verbose_name='Endereco')),
                ('numero', models.CharField(max_length=8, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=128, null=True, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_ti.secretaria')),
            ],
        ),
    ]
