# Generated by Django 4.2.5 on 2023-10-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0008_secretaria_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='numero',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='setor',
            name='endereco',
            field=models.CharField(max_length=128, null=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=150, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=150, verbose_name='Logradouro'),
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='Logradouro',
        ),
    ]
