# Generated by Django 4.2.5 on 2023-10-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0009_remove_secretaria_bairro_remove_secretaria_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_ti.secretaria', verbose_name='Secretaria'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_ti.setor', verbose_name='Setor'),
        ),
    ]
