# Generated by Django 4.1.7 on 2023-10-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_ti', '0010_alter_ordemdeservico_secretaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='endereco',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='os_ti.endereco'),
        ),
    ]
